spring:
  data:
    mongodb:
      uri: "mongodb+srv://qmean:rlarbals9907@brainpixmongo.hxqdd.mongodb.net/allright"
  cloud:
    aws:
      region:
        static: "us-east-1"
      s3:
        region: "us-east-1"
        bucket: "inha-capstone-14-bucket"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
ai:
  request:
    url: "https://54.205.90.224/ai"
