spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/allright"

  cloud:
    aws:
      region:
        static: "us-east-1"
      s3:
        region: "us-east-1"
        bucket: "inha-capstone-14-bucket"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

ai:
  request:
    url: "localhost:8000"
